

services:
  kombi-web-appliance:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kombi-web-appliance
    restart: always
    pull_policy: always
    networks:
      - kombi-network
    ports:
      - "3005:3005"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://kombi-datacenter:3002}
      - VITE_DATACENTER_WS_URL=${VITE_DATACENTER_WS_URL:-ws://kombi-datacenter:8080}
      - VITE_ANALYTICS_WS_URL=${VITE_ANALYTICS_WS_URL:-ws://kombi-analytics:3001}
      - VITE_APP_NAME=${VITE_APP_NAME:-Web Appliance}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 128M

networks:
  kombi-network:
    external: true
    name: kombi-network
