services:
  kombi-web-appliance:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kombi-web-appliance
    restart: always
    networks:
      - kombi-network
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 128M

networks:
  kombi-network:
    external: true
    name: kombi-network